version: "3.8"

services:
  nginx:
    image: nginx:1.24
    volumes:
      - ./nginx/conf.d:/nginx/conf.d
    ports:
      - "80:80"
    links:
      - app
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    volumes:
      - .:/app
